apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../apps/hello-app
patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Hello from dev!"
  - target:
      kind: Ingress
      name: hello-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello-app.dev.idp.localhost  # port 80
labels:
  - pairs:
      app.kubernetes.io/env: dev
images:
  - name: localhost:5001/hello-app
    newTag: dbab25f
