api:
  host: kargo.idp.localhost
  adminAccount:
    enabled: true
    passwordHash: "$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm"
    tokenSigningKey: "iwishtowashmyirishwristwatch"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls:
      enabled: false
controller:
  argocd:
    integrationEnabled: true
    namespace: argocd
  rollouts:
    integrationEnabled: true
