api:
  host: kargo.idp.localhost
  adminAccount:
    enabled: true
    passwordHash: "$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm"
    tokenSigningKey: "iwishtowashmyirishwristwatch"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls:
      enabled: false
controller:
  allowCredentialsOverHTTP: true
  gitClient:
    # Explicitly set before v1.12.0 where the default changes from
    # AlwaysRebase to RebaseOrMerge.
    pushIntegrationPolicy: AlwaysRebase
  argocd:
    integrationEnabled: true
    namespace: argocd
  rollouts:
    integrationEnabled: true
