name: Build and Push

on:
  workflow_call:
    inputs:
      registry:
        description: "Registry host"
        type: string
        default: "kind-registry:5000"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout IDP repo
        uses: actions/checkout@v4
        with:
          repository: admin/idp
          ref: main
          path: .idp
      - name: Build and push
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          .idp/scripts/build.sh \
            --registry "${{ inputs.registry }}" \
            --repo "${REPO_NAME}" \
            --context .
