apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitea

resources:
  - namespace.yaml

secretGenerator:
  - name: gitea-actions-runner-token
    envs:
      - secrets/runner-token.env
    options:
      disableNameSuffixHash: true

helmCharts:
  - name: gitea
    repo: https://dl.gitea.com/charts/
    version: "12.5.0"
    releaseName: gitea
    namespace: gitea
    includeCRDs: true
    valuesFile: values.yaml
