apiVersion: v1
kind: Service
metadata:
  name: registry-tls-proxy
  namespace: registry
spec:
  selector:
    app: registry-tls-proxy
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
