apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-actions-runner-config
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: .runner
      capacity: 1
      timeout: 3600
      labels:
        - "ubuntu-latest:docker://node:20-bookworm"
    cache:
      enabled: false
    container:
      network: ""
      privileged: false
      options:
      valid_volumes: []
