apiVersion: v1
kind: Secret
metadata:
  name: gitea-creds
  namespace: hello-app
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: http://gitea-http.gitea.svc.cluster.local:3000/admin/idp.git
  username: admin
  password: admin123
