apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: hello-app
  namespace: hello-app
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
