apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
  - ../../../../apps/hello-app

patches:
  - target:
      kind: Deployment
      name: hello-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Hello from qa!"
  - target:
      kind: Ingress
      name: hello-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello-app.qa.idp.localhost  # port 8080

labels:
  - pairs:
      app.kubernetes.io/env: qa
