apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kargo-api
  labels:
    app.kubernetes.io/part-of: idp
  annotations:
    idp.localhost/credentials-secret: kargo-api
    idp.localhost/credentials-keys: "username,password"
